/*
 * Copyright &#169; 2015 Manhattan Associates, Inc.  All Rights Reserved.
 *
 * Confidential, Proprietary and Trade Secrets Notice
 *
 * Use of this software is governed by a license agreement. This software
 * contains confidential, proprietary and trade secret information of
 * Manhattan Associates, Inc. and is protected under United States and
 * international copyright and other intellectual property laws. Use, disclosure,
 * reproduction, modification, distribution, or storage in a retrieval system in
 * any form or by any means is prohibited without the prior express written
 * permission of Manhattan Associates, Inc.
 *
 * Manhattan Associates, Inc.
 * 2300 Windy Ridge Parkway, 10th Floor
 * Atlanta, GA 30339 USA
 */

package com.github.prajan.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import javax.annotation.Generated;

@Generated(value = "Generated by EntityFramework")
@JsonIgnoreProperties(ignoreUnknown = true)
public class UniversityBaseDTO
{

    public static class KeyDTO
    {
        private String universityName;

        private String state;

        public KeyDTO()
        {
            super();
        }

        public KeyDTO(String universityName, String state)
        {
            this();
            this.universityName = universityName;
            this.state = state;
        }

        @JsonProperty(value = "UniversityName")
        public String getUniversityName()
        {
            return universityName;
        }

        public void setUniversityName(String universityName)
        {
            this.universityName = universityName;
        }

        @JsonProperty(value = "State")
        public String getState()
        {
            return state;
        }

        public void setState(String state)
        {
            this.state = state;
        }

        @Override
        public String toString()
        {
            return "KeyDTO{" +
                    "universityName='" + universityName + '\'' +
                    ", state='" + state + '\'' +
                    '}';
        }

    }

    private String universityName;

    private String state;

    private Integer foundingYear;


    public UniversityBaseDTO()
    {
    }

    public UniversityBaseDTO(KeyDTO key)
    {
        setUniversityName(key.universityName);
        setState(key.state);
    }


    @JsonProperty(value = "UniversityName")
    @ApiModelProperty(name = "UniversityName", value = "name of the university. Must be unique within a state")
    public String getUniversityName()
    {
        return universityName;
    }

    protected void setUniversityName(String universityName)
    {
        this.universityName = universityName;
    }

    @JsonProperty(value = "State")
    @ApiModelProperty(name = "State", value = "state in which the university is chartered")
    public String getState()
    {
        return state;
    }

    protected void setState(String state)
    {
        this.state = state;
    }

    @JsonProperty(value = "FoundingYear")
    @ApiModelProperty(name = "FoundingYear", value = "year the university was founded")
    public Integer getFoundingYear()
    {
        return foundingYear;
    }

    public void setFoundingYear(Integer foundingYear)
    {
        this.foundingYear = foundingYear;
    }


    @Override
    public boolean equals(Object o)
    {
        if (this == o)
            return true;
        if (o == null || getClass() != o.getClass())
            return false;
        if (!super.equals(o))
            return false;

        UniversityBaseDTO that = (UniversityBaseDTO) o;

        if (universityName != null ? !universityName.equals(that.universityName) : that.universityName != null)
            return false;
        if (state != null ? !state.equals(that.state) : that.state != null)
            return false;

        return true;
    }

    @Override
    public int hashCode()
    {
        int result = super.hashCode();

        result = 31 * result + (universityName != null ? universityName.hashCode() : 0);
        result = 31 * result + (state != null ? state.hashCode() : 0);
        return result;
    }

    @Override
    public String toString()
    {
        return "UniversityBaseDTO{" +
                ", universityName='" + universityName + '\'' +
                ", state='" + state + '\'' +
                ", foundingYear='" + foundingYear + '\'' +
                "} " + super.toString();
    }

}
